django-board/boards/urls.py
# 내가 새로 생성하는 파일

from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [

    path('', views.index, name='index'),
    path('new/', views.new, name='new'),  # 사용자의 입력을 받아서 게시글을 작성하는 곳
    # path('create/', views.create, name='create'),  # 입력받는 데이터를 전송 받고 실제 DB에 작성 및 사용자에서 피드백
    path('<int:board_id>/', views.detail, name='detail'),  # 특정 게시글로 들어가기 /boards/<id>
    path('<int:board_id>/delete/', views.delete, name='delete'),
    path('<int:board_id>/edit/', views.edit, name='edit'),  # 게시글 수정 페이지 렌더링
    # path('<int:id>/update/', views.update, name='update'),  # 사용자가 입력한 수정 데이더를 전송받고 실제 DB에 수정 후 저장


    # comments
    path('<int:board_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:board_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),  # boards/6/comments/2/delete -> 굉장히 명시적인 url




]

django-board/boards/models.py
from django.db import models
from imagekit.models import ProcessedImageField  # new
from imagekit.processors import Thumbnail  # new

# Create your models here.


class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
        upload_to='boards/images',  # 저장 위치 설정 ( media 이후의 경로 설정 )
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality': 90},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # admin 페이지에 데이터 보여지는 형태 지정
    def __str__(self):
        return f'{self.id}. {self.title}'
    

# 새로운 app 을 생성하지 않고 class 를 추가하여 board 의 DB 에 추가?
class Comment(models.Model):
    content = models.TextField()  # 댓글의 내용
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f'<Board({self.board_id}): Comment({self.id} - {self.content})>'

django-board/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from .models import Board, Comment
# Create your views here.


@require_http_methods(['GET'])
def index(request):
    # Board 의 전체 데이터를 불러온다 - QuerySet (list와 유사한 형태지만 실제 list는 아님)
    boards = Board.objects.all()
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)


# 사용장 입력을 받는 페이지 렌더링
@require_http_methods(['GET', 'POST'])
def new(request):
    # GET
    # POST
    # print(request.method) => GET
    if request.method == 'GET':
        return render(request, 'boards/new.html')
    else:
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')    # 사용자로 부터 받는 데이터의 종류가 파일 이미지이다.
        board = Board(title=title, content=content, image=image)
        board.save()
        return redirect('boards:detail', board.id)



# 데이터를 받아서 실제 DB에 작성
# def create(request):
#     title = request.POST.get('title')
#     content = request.POST.get('content')
#     board = Board(title=title, content=content)
#     board.save()
#
#     return redirect('boards:detail', board.id)   # 새로운 글을 작성해서 제출 누르면 바로 상세 페이지로 연결


# 특정 게시글 하나만 가지고 오기
# localhost:8000/boards/<id>/
@require_http_methods(['GET'])
def detail(request, board_id):
    # Board 클래스를 사용해서 id 값에 맞는 데이터를 가지고 온다.
    # context 로 넘겨서 detail.html 페이지에서 title 과 context를 출력해본다.

    # board = Board.objects.get(id=id)   # get => 특정 id 값으로 접근 (주로 pk 같이 유일한 값)
    board = get_object_or_404(Board, id=board_id)
    comments = board.comment_set.order_by('-id').all()
    context = {'board': board, 'comments':comments}
    return render(request, 'boards/detail.html', context)


@require_http_methods(['POST'])  # POST 로 들어올 때만 로직이 돌고 아니면 에러 발생. 그래서 if 문 안 써도 된당
def delete(request, board_id):
    # GET 요청으로 들어오면 detail page 로 다시 redirect
    # POST 요청으로 들어오면 정상 삭제

    # if request.method == 'GET':
    #     return redirect('boards:detail', id)
    #
#    else:
        board = Board.objects.get(id=board_id)
        board.delete()
        return redirect('boards:index')


# 게시글 수정 페이지 렌더링
@require_http_methods(['GET', 'POST'])
def edit(request, board_id):
    # GET
    # POST
    # board = Board.objects.get(id=id)  # 아래 if 문과 else 문에 중복되기 때문에 밖으로 꺼내서 한 번만 처리하기 Don't Repeat Yourself
    board = get_object_or_404(Board, id=board_id)
    # 1. 사용자의 요청이 GET인지 POST 인지 확인
    if request.method =='GET':
        # 2. GET 요청이면 사용자에게 수정할 페이지 보여준다.
        context = {'board': board}
        return render(request, 'boards/edit.html', context)
    else:
        # 3. POST 요청이면 사용자가 보낸 데이터를 받아서 수정한 뒤 detail page 로 redirect 한다.
        title = request.POST.get('title')
        content = request.POST.get('content')  # 사용자가 보낸 title 과 content 받기
        image = request.FILES.get('image')  # new
        # 수정 로직
        board.title = title
        board.content = content
        board.image = image
        board.save()
        return redirect('boards:detail', board_id)  # f'/boards/{id}/' 이거를 이름 지정한 걸로 바꾸기


# def update(request, id):
#     # id 값에 맞는 board 데이터를 위에서 주어진 title 과 content 에 맞게
#     # 수정한 뒤 저장하는 로직
#     title  = request.POST.get('title')
#     content = request.POST.get('content')  # 사용자가 보낸 title과 content 받기
#     # id 값에 맞는 데이터 가져오기
#     board = Board.objects.get(id=id)
#     # 2. 해당 데이터의 내용을 주어진 title, content 로 지정
#
#     board.title = title
#     board.content = content
#     # 3. 저장
#     board.save()
#     return redirect('boards:detail', id)  # f'/boards/{id}/' 이거를 이름 지정한 걸로 바꾸기


def comment_create(request, board_id):
    # 댓글 생성하는 로직
    content = request.POST.get('content')
    comment = Comment()
    comment.board_id = board_id
    comment.content = content
    comment.save()

    return redirect('boards:detail', board_id)


@require_POST
def comment_delete(request, board_id, comment_id):
    # 댓글 삭제 로직
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect('boards:detail', board_id)

django-board/boards/templates/boards/create.html
{%  extends 'boards/base.html' %}

    {%  block body %}
    <h1>성공적으로 작성되었습니다.</h1>

    {% endblock %}

django-board/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}


    {% block body %}
    <h1>Detail</h1>
 {% if board.image %}
    <img src="{{ board.image.url }}" alt="{{ board.image.name }}">
{% else %}
<p>이미지가 없습니다.</p>
{% endif %}
    <h2>{{ board.title }}</h2>
    <p>{{ board.id }}번 째 글</p>
    <p>{{ board.created_at}}</p>
<hr />
    <p>{{ board.content }}</p>
<hr />

    <form action="{% url 'boards:comment_create' board.id %}" method="post">
             {% csrf_token %}
        <input type="text" name="content" placeholder="댓글을 입력해주세요."/>
                           <!--name값을 views.py의 def comment_create의 POST.get 값으로 넘겨줘야 한다.-->
        <input type="submit" value="댓글달기" />
        <hr/>
    </form>

    <p>
        <b>댓글목록</b>
    </p>
    {% for comment in comments %}
        <li>{{ comment.content }}</li>
        <form action="{% url 'boards:comment_delete' board.id comment.id %}" method="post">
                {% csrf_token %}
            <input type="submit" value="댓글삭제" />
        </form>




        <!--댓글이 없으면 '댓글이 없습니다.' 출력-->
        {% empty %}
        <p>댓글이 없습니다.</p>

    {% endfor %}

<hr>
    <a href="{% url 'boards:index' %}" class = "btn btn-light">뒤로가기</a>
    <!--<a href="/boards/{{board.id}}/delete/">[삭제하기]</a>-->
        <!--위의 get 요청을 post 로 바꾸기 !-->
    <form action="{% url 'boards:delete' board.id %}" method="post">
             {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="삭제하기" />
    </form>

    <a href="{% url 'boards:edit' board.id %}" class="btn btn-warning">수정하기</a>


    {% endblock %}

django-board/boards/templates/boards/edit.html
{% extends 'boards/base.html' %}

{% block body %}

    <h1>Edit</h1>
    <form action="{% url 'boards:edit' board.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title">Title</label> <br />
        <!--for 는 해당 라벨의 id를 찾아감-->
        <input name ="title" id="title" type="text" value="{{ board.title }}"/><br />
        <label for="content">Content</label><br />
        <textarea name="content" id="content">{{ board.content}}</textarea><br />
         <!--name 속성은 데이터를 보낼 때 데이터 함께 보내는데 데이터의 이름을 name으로 지정 > textarea에 담겨있는 데이터 key 값-->
        <input type="file" name="image" accept="image/*">
        <input type="submit" />

    </form>

    <a href="{% url 'boards:index' %}">뒤로 가기</a>
{% endblock %}

django-board/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}



    <h1>Welcome to boards</h1>
<hr />


    {% for board in boards %}
        <p>글 번호 : {{ board.id}}</p>
        <p>글 제목 : {{ board.title }}</p>
        <a href="{% url 'boards:detail' board.id %}">[상세글 보러가기]</a>
      <!-- href="/boards/{{ board.id}}"/-->
        <hr />
    {% endfor%}

        <a href="{% url 'boards:new' %}">새로운 글 작성하러 가기</a>
        <!--href="/boards/new/"-->
    {% endblock %}

django-board/boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}

    <h1>NEW</h1>
    <form action="{%  url 'boards:new' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title">Title</label> <br />
        <!--for 는 해당 라벨의 id를 찾아감-->
        <input name ="title" id="title" type="text" /><br />
        <label for="content">Content</label><br />
        <textarea name="content" id="content"></textarea><br />
         <!--name 속성은 데이터를 보낼 때 데이터 함께 보내는데 데이터의 이름을 name으로 지정 > textarea에 담겨있는 데이터 key 값-->
        <input name="image" type="file" accept="image/*" />
        <!--이미지 받는 태그-->
        <input type="submit" />

    </form>

    <a href="{% url 'boards:index' %}">뒤로 가기</a>
{% endblock %}