movie-CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movie-CRUD/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [

    path('', views.index, name = 'index'),  # 목록
    path('create/', views.create, name='create'),  # method 분기
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/update/', views.update, name='update'),
    path('<int:movie_id>/delete/', views.delete, name='delete'),

    ]

movie-CRUD/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_origin = models.CharField(max_length=100)
    vote_count = models.IntegerField()
    open_date = models.CharField(max_length=30)
    genre = models.CharField(max_length=20)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

movie-CRUD/movies/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from .models import Movie
# Create your views here.

@require_GET
def index(request):

    movies = Movie.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request, movie_id):

    if request.method =='GET':
        return render(request, 'movies/create.html')
    else:
        title = request.POST.get('title')
        title_origin = request.POST.get('title_origin')
        vote_count = request.POST.get('vote_count')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        score= request.POST.get('score')
        poster_url= request.POST.get('poster_url')
        description = request.POST.get('description')

        movie = Movie(title=title, title_origin=title_origin, vote_count=vote_count,
                      open_date=open_date, genre=genre,score=score,poster_url=poster_url,description=description)
        movie.save()
        return redirect('movies:detail', movie_id)


@require_GET
def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    context = {'movie':movie}
    return render(request, 'movies/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)

    if request.method=='GET':
        context = {'movie': movie}
        return render(request, 'movies/update.html', context)

    else:
        title = request.POST.get('title')
        title_origin = request.POST.get('title_origin')
        vote_count = request.POST.get('vote_count')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')


        movie.title = title
        movie.title_origin= title_origin
        movie.vote_count = vote_count
        movie.open_date = open_date
        movie.genre = genre
        movie.score = score
        movie.poster_url = poster_url
        movie.description = description

        movie.save()
        return redirect('movies:detail', movie_id)


def delete(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    movie.delete()
    return redirect('movies:index')

movie-CRUD/movies/templates/movies/base.html
 <!--boards에서 만드는 모든 html이 이 base.html을 상속받아 작성되도록 설정!-->

<!-- boards/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>CRUD</title>
</head>
<body>
    <div class="container">
          <!--이 템플릿을 상속받은 html들은 이 구역에 코드를 작성 해야된다.-->
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movie-CRUD/movies/templates/movies/create.html
{% extends 'movies/base.html' %}

{% block body%}

    <h1>New Movie Register</h1>
    <form action="{% url 'movies:create' %}" method="post">
     {% csrf_token %}
<label for="title">Title</label> <br />
<input name="title" id="title" type="text" /> <br />

<label for="title_origin">title_origin</label> <br />
<input name="title_origin" id="title_origin" type="text" /> <br />

<label for="vote_count">vote_count</label> <br />
<input name="vote_count" id="vote_count" type="number" /> <br />

<label for="open_date">open_date</label> <br />
<input name="open_date" id="open_date" type="date" /> <br />

<label for="genre">genre</label> <br />
<input name="genre" id="genre" type="text" /> <br />

<label for="score">score</label> <br />
<input name="score" id="score" type="number" min="0" max="5" step="0.5"/> <br />


<label for="poster_url">poster_url</label> <br />
<input name="poster_url" id="poster_url" type="text" /> <br />

<label for="description">description</label><br />
  <textarea name="description" id="description"></textarea><br />

<input type="submit" />

</form>
<a href="{% url 'movies:index' %}">[메인 페이지]</a>

{% endblock %}

movie-CRUD/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}


{% block body %}

<h1>Detail Page</h1>
<h2>{{ movie.title}} </h2>
<hr />

<p>title: {{ movie.title_origin }}</p>
<p>vote_count: {{ movie.vote_count }}</p>
<p>open_date: {{ movie.open_date }}</p>
<p>genre: {{ movie.genre }}</p>
<p>score: {{ movie.score }}</p>
<p>poster_usr: {{ movie.poster_url }}</p>
<p>description: {{ movie.description }}</p>

<hr />

<a href="{% url 'movies:index' %}" class="btn btn-light">목록</a>

<a href="{% url 'movies:update' movie.id %}" class="btn btn-warning">수정</a>

<form action="{% url 'movies:delete' movie.id %}" method="post">
  {% csrf_token %}
    <input  class="btn btn-danger" type="submit" value="삭제">
</form>

{% endblock%}

movie-CRUD/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}


 <h1>Welcome to movies page</h1>
<hr />
<a href="{% url 'movies:create' %}">[새 영화 등록]</a>
<hr />


    {% for movie in movies %}
        <p><b>{{ movie.title}}</b></p>
        <p>개봉일 : {{ movie.open_date }}</p>
        <p>장르 : {{ movie.genre }}</p>

        <a href="{% url 'movies:detail' movie.id %}">[Go Detail]</a>
<hr />
    {% endfor%}


    {% endblock %}

movie-CRUD/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block body%}

    <h1>New Movie Register</h1>
    <form action="{% url 'movies:create' %}" method="post">
     {% csrf_token %}
<label for="title">Title</label> <br />
<input name="title" id="title" type="text" /> <br />

<label for="title_origin">title_origin</label> <br />
<input name="title_origin" id="title_origin" type="text" /> <br />

<label for="vote_count">vote_count</label> <br />
<input name="vote_count" id="vote_count" type="number" /> <br />

<label for="open_date">open_date</label> <br />
<input name="open_date" id="open_date" type="date" /> <br />

<label for="genre">genre</label> <br />
<input name="genre" id="genre" type="text" /> <br />

<label for="score">score</label> <br />
<input name="score" id="score" type="number" /> <br />


<label for="poster_url">poster_url</label> <br />
<input name="poster_url" id="poster_url" type="text" /> <br />

<label for="description">description</label><br />
  <textarea name="description" id="description"></textarea><br />

<input type="submit" />

</form>


{% endblock %}

movie-CRUD/movies/templates/movies/update.html
{% extends 'movies/base.html' %}

{% block body%}

    <h1>Update Page</h1>
    <form action="{% url 'movies:update' movie.id %}" method="post">
     {% csrf_token %}
<label for="title">Title</label> <br />
<input name="title" id="title" type="text" value="{{ movie.title}}"/> <br />

<label for="title_origin">title_origin</label> <br />
<input name="title_origin" id="title_origin" type="text" value="{{ movie.title_origin }}" /> <br />

<label for="vote_count">vote_count</label> <br />
<input name="vote_count" id="vote_count" type="number" value="{{ movie.vote_count }}"/> <br />

<label for="open_date">open_date</label> <br />
<input name="open_date" id="open_date" type="date" value="{{ movie.open_date}}" /> <br />

<label for="genre">genre</label> <br />
<input name="genre" id="genre" type="text" value="{{ movie.genre }}" /> <br />

<label for="score">score</label> <br />
<input name="score" id="score" type="number" value="{{ movie.score }}" /> <br />


<label for="poster_url">poster_url</label> <br />
<input name="poster_url" id="poster_url" type="text" value="{{ movie.poster_url }}"/> <br />

<label for="description">description</label><br />
  <textarea name="description" id="description">{{ movie.description}}</textarea><br />

<input type="submit" />

</form>
<a href="{% url 'movies:detail' movie.id %}">뒤로가기</a>

{% endblock %}